bug:
    - '(defekt|defect|mangel|mängel|shortcoming|schwäche|weakness|störung|disturbance|fehlfunktion|malfunction|fehlerhaftigkeit|fehlerhaft|fault|error|faultiness|unzulänglichkeit|unzugänglich|inadequacy|bug|fehler|\
        Defekt|Defect|Mangel|Mängel|Shortcoming|Schwäche|Weakness|Störung|Disturbance|Fehlfunktion|Malfunction|Fehlerhaftigkeit|Fehlerhaft|Fault|Error|Faultiness|Unzulänglichkeit|Unzugänglich|Inadequacy|Bug|Fehler|\
        DEFEKT|DEFECT|MANGEL|MÄNGEL|SHORTCOMING|SCHWÄCHE|WEAKNESS|STÖRUNG|DISTURBANCE|FEHLFUNKTION|MALFUNCTION|FEHLERHAFTIGKEIT|FEHLERHAFT|FAULT|ERROR|FAULTINESS|UNZULÄNGLICHKEIT|UNZUGÄNGLICH|INADEQUACY|BUG|FEHLER)'

documentation:
    - '(dokumentation|documentation|aufzeichnung|record|bericht|report|protokoll|protocol|\
        Dokumentation|Documentation|Aufzeichnung|Record|Bericht|Report|Protokoll|Protocol|\
        DOKUMENTATION|DOCUMENTATION|AUFZEICHNUNG|RECORD|BERICHT|REPORT|PROTOKOLL|PROTOCOL)'
    

enhancement:
    - '(verbesserung|improvement|erweiterung|extension|neuerung|erneuerung|innovation|merkmal|feature|funktion|function|anforderung|requirement|\
        Verbesserung|Improvement|Erweiterung|Extension|Neuerung|Erneuerung|Innovation|Merkmal|Feature|Funktion|Function|Anforderung|Requirement|\
        VERBESSERUNG|IMPROVEMENT|ERWEITERUNG|EXTENSION|NEUERUNG|ERNEUERUNG|INNOVATION|MERKMAL|FEATURE|FUNKTION|FUNCTION|ANFORDERUNG|REQUIREMENT)'

help wanted:
    - '(help|hilfe|\
        Help|Hilfe|\
        HELP|HILFE)'

question:
    - '(frage|question|fragen|questions|\
        Frage|Question|Fragen|Questions|\
        FRAGE|QUESTION|FRAGEN|QUESTIONS)'
