blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/RPiList/specials/discussions
    about: If you have ideas, ask questions and would like to have them answered and would like to show and tell something. then join the discussions