name: New Domains to Blocklists
description: Report a new Domain entry to Blocklists so that it is included in the Blocklists.
title: 'entry_request: '
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Domain(s)
      description: |
        - Describe which Domains should be included in the Blocklists
        - (Domain entry per line)
      render: shell
      placeholder: |
        test.com
        www.test.com
        *.test.com
        
        testing.org
        www.testing.org
        *.testing.org
    validations:
        required: true
  - type: textarea
    attributes:
      label: Reason
      description: For what reason should the Domains be included in the Blocklists?
    validations:
        required: true

