name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
#  pull_request:
#    types: [opened, edited]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      issues: write
#      pull-requests: write
      
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.1 #May not be the latest version
      with:
        configuration-path: .github/labeler.yml
        include-title: 1
        sync-labels: 1
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
